spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
          routes:
            - id: user-service
              uri: lb:http://USER-SERVICE
              predicates:
                - Path=/user-service/**

server:
  port: 8222
