spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
          routes:
            - id: user-auth
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/auth/**
            - id: user-users
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
            - id: board-workspaces
              uri: lb://BOARD-SERVICE
              predicates:
                - Path=/api/v1/workspaces/**
            - id: board-invitations
              uri: lb://BOARD-SERVICE
              predicates:
                - Path=/api/v1/invitations/**
            - id: board-boards
              uri: lb://BOARD-SERVICE
              predicates:
                - Path=/api/v1/boards/**
            - id: task-columns
              uri: lb://TASK-SERVICE
              predicates:
                - Path=/api/v1/columns/**
            - id: task-tasks
              uri: lb://TASK-SERVICE
              predicates:
                - Path=/api/v1/tasks/**
            - id: notification-notifications
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/v1/notifications/**
            - id: websocket-service
              uri: lb://WEBSOCKET-SERVICE
              predicates:
                - Path=/ws/**

server:
  port: 8222
