spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/user_service_db
    username: gabriel
    password: gabriel
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: userDto:io.github.ggabriel67.user.user.UserDto

server:
  port: 8090
