services:
  user-service-db:
    container_name: user-service-db
    image: postgres
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: gabriel
    volumes:
      - user-service-postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - kanvas-net
    restart: unless-stopped

  board-service-db:
    container_name: board-service-db
    image: postgres
    environment:
      POSTGRES_DB: board_service_db
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: gabriel
      PGDATA: /var/lib/postgresql/data
    volumes:
      - board-service-postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
      - kanvas-net
    restart: unless-stopped

  task-service-db:
    container_name: task-service-db
    image: postgres
    environment:
      POSTGRES_DB: task_service_db
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: gabriel
      PGDATA: /var/lib/postgresql/data
    volumes:
      - task-service-postgres:/var/lib/postgresql/data
    ports:
      - 5435:5432
    networks:
      - kanvas-net
    restart: unless-stopped

  notification-service-db:
    container_name: notification-service-db
    image: postgres
    environment:
      POSTGRES_DB: notification_service_db
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: gabriel
      PGDATA: /var/lib/postgresql/data
    volumes:
      - notification-service-postgres:/var/lib/postgresql/data
    ports:
      - 5436:5432
    networks:
      - kanvas-net
    restart: unless-stopped

  pgadmin:
    container_name: kanvas-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - kanvas-net
    restart: unless-stopped

  kafka:
    image: bitnami/kafka
    container_name: kanvas-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@localhost:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - kanvas-net

networks:
  kanvas-net:
    driver: bridge

volumes:
  user-service-postgres:
  board-service-postgres:
  task-service-postgres:
  notification-service-postgres:
  pgadmin:
